services:
  - type: web
    name: 4-dars-app
    env: node
    buildCommand: npm install && cd backend && npm install && cd ../frontend && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
