services:
  - type: web
    name: 4-dars-main
    env: node
    buildCommand: npm install && cd backend && npm install && cd ../frontend && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: BACKEND_PORT
        value: 4545
  
  - type: background
    name: 4-dars-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm run dev
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4545
